vim.opt.showmatch = true -- Show matching bracket for a brief moment
vim.opt.autowrite = true -- auto write buffer on file change
vim.opt.ignorecase = true -- ignore case on search
vim.opt.hlsearch = false -- don't highlight all matches
vim.opt.incsearch = true -- highlight during search
vim.opt.tabstop = 4 -- number of spaces for a tab
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4 -- number of spaces for auto indent
vim.opt.expandtab = false
vim.opt.number = true -- line number
vim.opt.relativenumber = true -- relative line number
vim.opt.wildmenu = true
vim.opt.wildmode = { "longest:full", "full" } -- on first tab open wildmenu, on next move through the menu
vim.opt.cursorline = true
vim.opt.scrolloff = 1 -- keep N lines above or below when scrolling
vim.opt.showcmd = true -- show partial commands in status line
vim.opt.showmode = true -- show the current mode
vim.opt.smartindent = true
vim.opt.splitright = true -- put new window on right side on vsplit
vim.opt.splitbelow = true -- put new window below on split
vim.opt.errorbells = false -- disable bell on error
vim.opt.wrap = false
vim.opt.termguicolors = true -- enable 24-bit colors
vim.opt.completeopt = { "menu", "menuone", "noselect" } -- insert mode completion menu
vim.opt.list = true
vim.opt.listchars = { tab = " ", space = "·", eol = "󰌑", trail = "␠" } -- indent guide lines
vim.opt.cursorcolumn = true -- highlight the current column
vim.opt.updatetime = 4000
vim.opt.undofile = true
vim.opt.swapfile = true
vim.opt.laststatus = 3 -- enable global status line
vim.opt.signcolumn = "yes"
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.foldenable = false
vim.opt.foldlevelstart = 99
-- vim.opt.pumblend = 10 -- popup menu blend
vim.opt.fillchars = "eob: "
-- vim.opt.winblend = 10
vim.opt.cmdheight = 1

vim.g.mapleader = " "
vim.g.ftplugin_sql_omni_key = "<C-e>"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.o.guifont = "Iosevka:h16" -- text below applies for VimScript
